### ISSUE TITLE
Switch to modern bcrypt implementation

### ISSUE THREAD

**Issue by Leont** [cmanley/p5-PHP-Functions-Password#3]
This module is currently using `Crypt::Eksblowfish::Bcrypt` which is essentially unmaintained for the past decade. In particular, the rest of the world upgraded to the `2b` variety of bcrypt back in 2014. It also doesn't support `2y` passwords as sometimes used in php.

I've recently released [Crypt::Bcrypt](https://metacpan.org/pod/Crypt::Bcrypt), which does support modern varieties of bcrypt.

**Comment by cmanley** [comment]
Thanks for your contribution. I'll see if I can use your new module, especially since it's more up to date.

Since bcrypt uses a cost parameter, and has 4 different possible algorithms, you could add a (bcrypt_)needs_rehash function to your new module if you like. I could use that in the password_needs_rehash function. 
I now remember that I asked you for something similar in Crypt::Argon2 long ago which you implemented.
A bcrypt needs_rehash function could check if  the algorithm is up to date (either 2b or 2y) and if the cost has changed.
In this module, the password_needs_rehash function checks if the algorithm is 2y as that is the only algorithm supported by PHP. But I think I should update it to 'tolerate' 2b too as an algorithm not requiring a rehash, at least if PHP can deal with it.

B.t.w. this module isn't using Crypt::Eksblowfish::Bcrypt directly though but instead uses some copied and slightly modified functions (for the custom base64 encoding/decoding) from it. I can't remember though if I modified them functionally but I haven't been able to create a test case yet that proves that the Perl bcrypted string (with the $2y$ signature) can't be verified by PHP (or vice versa).

I have 2 more questions about your module:
Does it accept passwords longer than 72 characters and simply ignore what's more (as PHP does)?
Does it generate a salt if no salt option is provided? Since PHP 7, the salt option of password_hash() is deprecated, so I guess they don't even trust users to generate good enough salts. Password.pm uses Crypt::OpenSSL::Random::random_bytes(16) and then the custom bcrypt base64 encoding of that.

**Comment by Leont** [comment]
> Since bcrypt uses a cost parameter, and has 4 different possible algorithms, you could add a (bcrypt_)needs_rehash function to your new module if you like. I could use that in the password_needs_rehash function.
I now remember that I asked you for something similar in Crypt::Argon2 long ago which you implemented.

Maybe. I considered adding something like:
```
sub bcrypt_needs_rehash {
    my ($hash, $type, $cost) = @_;
    if ($hash =~ / \A \$ (2[abxy]) \$ (\d{2}) \$ /x) {
        return 0 if $1 eq $type && $2 >= $cost;
    }
    return 1;
}
```

but wasn't sure if it was useful enough in this case also because it's fairly simple to implement yourself if you want a more specific behavior.

> Does it accept passwords longer than 72 characters and simply ignore what's more (as PHP does)?

It does not accept longer passwords (and is documented not to do so). This is a fundamental property of bcrypt.

> Does it generate a salt if no salt option is provided?

No. This module intends to to one thing and one thing only: bcrypt.

**Comment by cmanley** [comment]
Ok thanks. I'll let you know when the new version of this module is ready.

**Comment by cmanley** [comment]
Done in that latest version: v1.13.
The needs_rehash function was implemented slightly differently to your example in order to emulate the behavior of PHP as close as possible. PHP checks for differences in type, cost, etc. and not which is better or worse than the other.
So in your example it would be:
```return 0 if $1 eq $type && $2 != $cost;```
